name: Update YouTube Music Profile

on:
  schedule:
    - cron: '0 12 * * *' # Daily at noon
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 yt-dlp

      - name: Create YouTube Music profile scraper
        run: |
          cat > yt_music_profile.py << 'EOF'
          import requests
          import json
          import re
          from datetime import datetime
          
          def get_youtube_channel_info():
              try:
                  # Your YouTube Music profile
                  channel_handle = "yuotosaka9092"
                  
                  # Create profile data
                  profile_data = {
                      "channel_name": "yuotosaka9092",
                      "channel_url": f"https://music.youtube.com/@{channel_handle}",
                      "profile_type": "Music Profile",
                      "last_updated": datetime.now().strftime("%B %d, %Y")
                  }
                  
                  return profile_data
                  
              except Exception as e:
                  print(f"Error: {e}")
                  return {
                      "channel_name": "yuotosaka9092",
                      "channel_url": "https://music.youtube.com/@yuotosaka9092",
                      "profile_type": "Music Profile",
                      "last_updated": datetime.now().strftime("%B %d, %Y")
                  }
          
          def create_profile_section(profile_data):
              section = f"""
          ## 🎵 My YouTube Music Profile
          
          <div align="center">
          
          <table>
          <tr>
          <td align="center" width="50%">
          
          **🎤 Channel**  
          [`@{profile_data['channel_name']}`]({profile_data['channel_url']})
          
          </td>
          <td align="center" width="50%">
          
          **🎶 Platform**  
          `{profile_data['profile_type']}`
          
          </td>
          </tr>
          <tr>
          <td align="center" colspan="2">
          
          **⏰ Profile Updated**  
          `{profile_data['last_updated']}`
          
          </td>
          </tr>
          </table>
          
          <br>
          
          [![YouTube Music Profile](https://img.shields.io/badge/YouTube%20Music-@yuotosaka9092-red?style=for-the-badge&logo=youtube-music&logoColor=white)]({profile_data['channel_url']})
          
          [![Listen on YouTube Music](https://img.shields.io/badge/🎵_Listen_Along-FF0000?style=for-the-badge&logo=youtube-music&logoColor=white)]({profile_data['channel_url']})
          
          </div>
          
          ---
          """
              return section.strip()
          
          if __name__ == "__main__":
              profile_data = get_youtube_channel_info()
              section = create_profile_section(profile_data)
              
              with open('youtube_music_section.md', 'w', encoding='utf-8') as f:
                  f.write(section)
              
              print("YouTube Music profile section created successfully!")
              print(f"Profile: @{profile_data['channel_name']}")
          EOF

      - name: Generate YouTube Music section
        run: python yt_music_profile.py

      - name: Update README
        run: |
          # Remove existing YouTube Music section if it exists
          sed -i '/## 🎵 My YouTube Music Profile/,/^---$/d' README.md
          
          # Insert the new section after the profile views badge
          sed -i '/komarev.com\/ghpvc/r youtube_music_section.md' README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "YouTube Music Profile Bot"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "🎵 Update YouTube Music profile section"
            git push
          else
            echo "No changes detected"
          fi